from PyQt6.QtCore import QRect, QSize, Qt, QMetaObject, QCoreApplication
from PyQt6.QtGui import QFont, QAction
from PyQt6.QtWidgets import QSlider, QWidget, QPushButton, QLabel, QMenuBar, \
    QMenu, QHBoxLayout, QStatusBar, QScrollArea, QGridLayout, QSizePolicy, QToolBar, QLineEdit
from pylab import *


class EditImageView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1024)
        font = QFont()
        MainWindow.setFont(font)

        # определение центрального виджета
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 940, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.greeting = QLabel(self.scrollAreaWidgetContents)
        font = QFont()
        font.setPointSize(22)
        self.greeting.setFont(font)
        self.greeting.setGeometry(QRect(360, 190, 900, 28))
        self.greeting.setText("Для начала работы выберите файл, с которым вы хотите поработать!")

        self.label = QLabel(self.scrollAreaWidgetContents)
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(360, 190, 61, 15))

        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("margin: auto; \n"
                                 "\n"
                                 "padding: 10px;")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)

        self.scrollArea_3 = QScrollArea(self.centralwidget)
        self.scrollArea_3.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QSize(942, 100))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 940, 100))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setVisible(False)

        self.scrollArea_2 = QScrollArea(self.centralwidget)
        self.scrollArea_2.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 940, 85))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.pushButton_Undo = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_Undo.setGeometry(QRect(90, 30, 61, 31))
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Undo.setFont(font)
        self.pushButton_Undo.setObjectName("pushButton_3")

        self.pushButton_Frame = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_Frame.setGeometry(QRect(160, 30, 161, 31))
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Frame.setFont(font)
        self.pushButton_Frame.setObjectName("pushButton_5")

        self.pushButton_Finish = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_Finish.setGeometry(QRect(10, 30, 61, 31))
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Finish.setFont(font)
        self.pushButton_Finish.setObjectName("pushButton_4")
        self.horizontalLayoutWidget = QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QRect(680, 20, 201, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Reduce = QPushButton(self.horizontalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Reduce.setFont(font)
        self.pushButton_Reduce.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_Reduce)
        self.pushButton_Enhance = QPushButton(self.horizontalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Enhance.setFont(font)
        self.pushButton_Enhance.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton_Enhance)
        self.pushButton_Init = QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_Init.setGeometry(QRect(330, 30, 93, 31))
        font = QFont()
        font.setPointSize(10)
        self.pushButton_Init.setFont(font)
        self.pushButton_Init.setObjectName("pushButton_Init")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 1, 0, 1, 1)

        # Удаление шумов
        self.h_label = QLabel(self.scrollAreaWidgetContents_3)
        self.h_label.setGeometry(QRect(680, 10, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.h_label.setFont(font)
        self.h_label.setObjectName("label_8")
        self.h_label.setVisible(False)
        self.sld_h = QSlider(Qt.Orientation.Horizontal, self.scrollAreaWidgetContents_3)
        self.sld_h.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.sld_h.setGeometry(760, 10, 100, 21)
        self.sld_h.setVisible(False)

        self.tws_label = QLabel(self.scrollAreaWidgetContents_3)
        self.tws_label.setGeometry(QRect(680, 40, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.tws_label.setFont(font)
        self.tws_label.setObjectName("label_9")
        self.tws_label.setVisible(False)
        self.sld_tws = QSlider(Qt.Orientation.Horizontal, self.scrollAreaWidgetContents_3)
        self.sld_tws.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.sld_tws.setGeometry(760, 40, 100, 21)
        self.sld_tws.setVisible(False)

        self.stw_label = QLabel(self.scrollAreaWidgetContents_3)
        self.stw_label.setGeometry(QRect(680, 70, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.stw_label.setFont(font)
        self.stw_label.setObjectName("label_10")
        self.stw_label.setVisible(False)
        self.sld_stw = QSlider(Qt.Orientation.Horizontal, self.scrollAreaWidgetContents_3)
        self.sld_stw.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.sld_stw.setGeometry(760, 70, 100, 21)
        self.sld_stw.setVisible(False)

        self.undo_DN = QPushButton(self.scrollAreaWidgetContents_3)
        self.undo_DN.setGeometry(QRect(20, 10, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.undo_DN.setFont(font)
        self.undo_DN.setObjectName("pushButton_15")
        self.undo_DN.setVisible(False)
        self.Implement_DN = QPushButton(self.scrollAreaWidgetContents_3)
        self.Implement_DN.setGeometry(QRect(20, 50, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.Implement_DN.setFont(font)
        self.Implement_DN.setObjectName("pushButton_16")
        self.Implement_DN.setVisible(False)

        # Контрастирование
        self.g_min_label = QLabel(self.scrollAreaWidgetContents_3)
        self.g_min_label.setGeometry(QRect(680, 10, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.g_min_label.setFont(font)
        self.g_min_label.setObjectName("label_2")
        self.g_min_label.setVisible(False)
        self.g_max_label = QLabel(self.scrollAreaWidgetContents_3)
        self.g_max_label.setGeometry(QRect(680, 50, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.g_max_label.setFont(font)
        self.g_max_label.setObjectName("label_3")
        self.g_max_label.setVisible(False)
        self.g_min_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.g_min_textbox.setGeometry(QRect(760, 10, 113, 22))
        self.g_min_textbox.setObjectName("lineEdit")
        self.g_min_textbox.setVisible(False)
        self.g_max_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.g_max_textbox.setGeometry(QRect(760, 50, 113, 22))
        self.g_max_textbox.setObjectName("lineEdit_2")
        self.g_max_textbox.setVisible(False)
        self.undo_LC = QPushButton(self.scrollAreaWidgetContents_3)
        self.undo_LC.setGeometry(QRect(20, 10, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.undo_LC.setFont(font)
        self.undo_LC.setObjectName("pushButton_7")
        self.undo_LC.setVisible(False)
        self.Implement_LC = QPushButton(self.scrollAreaWidgetContents_3)
        self.Implement_LC.setGeometry(QRect(20, 50, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.Implement_LC.setFont(font)
        self.Implement_LC.setObjectName("pushButton_8")
        self.Implement_LC.setVisible(False)

        # Соляризация
        self.k_label = QLabel(self.scrollAreaWidgetContents_3)
        self.k_label.setGeometry(QRect(680, 10, 61, 21))
        font = QFont()
        font.setPointSize(12)
        self.k_label.setFont(font)
        self.k_label.setObjectName("label_4")
        self.k_label.setVisible(False)
        self.k_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.k_textbox.setGeometry(QRect(760, 10, 113, 22))
        self.k_textbox.setObjectName("lineEdit_3")
        self.k_textbox.setVisible(False)
        self.undo_S = QPushButton(self.scrollAreaWidgetContents_3)
        self.undo_S.setGeometry(QRect(20, 10, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.undo_S.setFont(font)
        self.undo_S.setObjectName("pushButton_9")
        self.undo_S.setVisible(False)
        self.Implement_S = QPushButton(self.scrollAreaWidgetContents_3)
        self.Implement_S.setGeometry(QRect(20, 50, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.Implement_S.setFont(font)
        self.Implement_S.setObjectName("pushButton_10")
        self.Implement_S.setVisible(False)

        # Бинаризация
        self.threshold_label = QLabel(self.scrollAreaWidgetContents_3)
        self.threshold_label.setGeometry(QRect(640, 10, 101, 21))
        font = QFont()
        font.setPointSize(12)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("label_5")
        self.threshold_label.setVisible(False)
        self.threshold_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.threshold_textbox.setGeometry(QRect(760, 10, 113, 22))
        self.threshold_textbox.setObjectName("lineEdit_4")
        self.threshold_textbox.setVisible(False)
        self.undo_B = QPushButton(self.scrollAreaWidgetContents_3)
        self.undo_B.setGeometry(QRect(20, 10, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.undo_B.setFont(font)
        self.undo_B.setObjectName("pushButton_11")
        self.undo_B.setVisible(False)
        self.Implement_B = QPushButton(self.scrollAreaWidgetContents_3)
        self.Implement_B.setGeometry(QRect(20, 50, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.Implement_B.setFont(font)
        self.Implement_B.setObjectName("pushButton_12")
        self.Implement_B.setVisible(False)

        # Препарирование
        self.low_border_label = QLabel(self.scrollAreaWidgetContents_3)
        self.low_border_label.setGeometry(QRect(630, 10, 111, 25))
        font = QFont()
        font.setPointSize(12)
        self.low_border_label.setFont(font)
        self.low_border_label.setObjectName("label_6")
        self.low_border_label.setVisible(False)
        self.high_border_label = QLabel(self.scrollAreaWidgetContents_3)
        self.high_border_label.setGeometry(QRect(630, 50, 111, 25))
        font = QFont()
        font.setPointSize(12)
        self.high_border_label.setFont(font)
        self.high_border_label.setObjectName("label_7")
        self.high_border_label.setVisible(False)
        self.low_border_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.low_border_textbox.setGeometry(QRect(760, 10, 113, 22))
        self.low_border_textbox.setObjectName("lineEdit_5")
        self.low_border_textbox.setVisible(False)
        self.high_border_textbox = QLineEdit(self.scrollAreaWidgetContents_3)
        self.high_border_textbox.setGeometry(QRect(760, 50, 113, 22))
        self.high_border_textbox.setObjectName("lineEdit_6")
        self.high_border_textbox.setVisible(False)
        self.undo_D = QPushButton(self.scrollAreaWidgetContents_3)
        self.undo_D.setGeometry(QRect(20, 10, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.undo_D.setFont(font)
        self.undo_D.setObjectName("pushButton_13")
        self.undo_D.setVisible(False)
        self.Implement_D = QPushButton(self.scrollAreaWidgetContents_3)
        self.Implement_D.setGeometry(QRect(20, 50, 93, 28))
        font = QFont()
        font.setPointSize(10)
        self.Implement_D.setFont(font)
        self.Implement_D.setObjectName("pushButton_14")
        self.Implement_D.setVisible(False)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_3.setVisible(False)
        self.gridLayout.addWidget(self.scrollArea_3, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 924, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)

        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QSize(500, 45))
        self.toolBar.setObjectName("toolBar")
        self.toolBar.setVisible(True)

        self.button_Denoise = QPushButton('Удаление шумов')

        self.button_LinearContrast = QPushButton('Линейное контрастирование')

        self.button_Solarization = QPushButton('Увеличение четкости мелких объектов(Соляризация)')

        self.button_Dissection = QPushButton('Увеличение четкости мелких объектов(Препарирование)')

        self.button_Binarization = QPushButton('Увеличение четкости крупных объектов(Бинаризация)')

        self.toolBar.addWidget(self.button_Denoise)
        self.toolBar.addWidget(self.button_LinearContrast)
        self.toolBar.addWidget(self.button_Solarization)
        self.toolBar.addWidget(self.button_Dissection)
        self.toolBar.addWidget(self.button_Binarization)

        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName("action")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName("action_2")
        self.action_Gray = QAction(MainWindow)
        self.action_Gray.setCheckable(True)
        self.action_Gray.setObjectName("action_3")
        self.menu.addAction(self.action_Open)
        self.menu.addAction(self.action_Save)
        self.menu_2.addAction(self.action_Gray)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Undo.setText(_translate("MainWindow", "Назад"))
        self.pushButton_Finish.setText(_translate("MainWindow", "Готово"))
        self.pushButton_Frame.setText(_translate("MainWindow", "Вырезать кадр"))
        self.pushButton_Reduce.setText(_translate("MainWindow", "Уменьшить"))
        self.pushButton_Enhance.setText(_translate("MainWindow", "Увеличить"))
        self.pushButton_Init.setText(_translate("MainWindow", "Исходник"))
        self.g_min_label.setText(_translate("MainWindow", "g_min:"))
        self.g_max_label.setText(_translate("MainWindow", "g_max:"))
        self.undo_LC.setText(_translate("MainWindow", "Назад"))
        self.Implement_LC.setText(_translate("MainWindow", "Выполнить"))
        self.menu_2.setTitle(_translate("MainWindow", "Режимы"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_Gray.setText(_translate("MainWindow", "Оттенок серого"))

        self.h_label.setText(_translate("MainWindow", "h:"))
        self.tws_label.setText(_translate("MainWindow", "tws:"))
        self.stw_label.setText(_translate("MainWindow", "stw:"))
        self.undo_DN.setText(_translate("MainWindow", "ОТМЕНА"))
        self.Implement_DN.setText(_translate("MainWindow", "ПОВТОР"))

        self.k_label.setText(_translate("MainWindow", "k:"))
        self.undo_S.setText(_translate("MainWindow", "Назад"))
        self.Implement_S.setText(_translate("MainWindow", "Выполнить"))

        self.threshold_label.setText(_translate("MainWindow", "порог:"))
        self.undo_B.setText(_translate("MainWindow", "Назад"))
        self.Implement_B.setText(_translate("MainWindow", "Выполнить"))

        self.low_border_label.setText(_translate("MainWindow", "x_min:"))
        self.high_border_label.setText(_translate("MainWindow", "x_max:"))
        self.undo_D.setText(_translate("MainWindow", "Назад"))
        self.Implement_D.setText(_translate("MainWindow", "Выполнить"))
